# Generated by Django 3.1.5 on 2021-04-25 05:49

import json
from pathlib import Path
from django.db import migrations, models


def import_leaders(apps, schema_editor):
    ShrimpyLeader = apps.get_model('trade', 'ShrimpyLeader')
    data = {}
    with open(Path(__file__).parent / '../fixtures/leaders.json', 'r') as f:
        data = json.loads(f.read())
    for obj in data:
        leader = ShrimpyLeader()
        leader.uid = obj["exchangeAccountId"]
        leader.name = obj["name"]
        leader.picture_hash = obj["profilePicture"]
        leader.exchange = obj["exchange"]
        leader.description = obj["description"]
        leader.performance_day = obj["performance24Hr"]["usd"]
        leader.performance_week = obj["performance7Day"]["usd"]
        leader.performance_month = obj["performance30Day"]["usd"]
        leader.followers_count = obj["followers"]
        leader.is_paid = obj["isPaidLeader"]
        leader.last_access_date = obj["lastSeen"]
        leader.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShrimpyLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('picture_hash', models.CharField(max_length=255)),
                ('exchange', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('performance_day', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('performance_week', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('performance_month', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('is_paid', models.BooleanField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_access_date', models.DateTimeField()),
            ],
        ),
        migrations.RunPython(import_leaders),
    ]
