# Generated by Django 3.1.5 on 2021-04-25 17:40

from django.db import migrations, models
from django.template.defaultfilters import slugify


def slugify_leaders(apps, schema_editor):
    ShrimpyLeader = apps.get_model('trade', 'ShrimpyLeader')
    for leader in ShrimpyLeader.objects.all():
        leader.slug = slugify(leader.name)
        leader.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shrimpyleader',
            name='slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(slugify_leaders),
    ]
